{% set name = "ale" %}
{% set version = "0.8.4" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ee726736410fd13a424b1389bf2557ed1f40e7f5caecfa9586051a0f54dbc815

build:
  number: 1
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - eigen
  host:
    - python
    - nlohmann_json
    - pip
  run:
    - networkx
    - nlohmann_json
    - numpy
    - pvl <=1.0
    - python
    - python-dateutil
    - scipy >=1.2.0
    - spiceypy >=2.3.0
    - pyyaml

test:
  imports:
    - ale
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - test -e $PREFIX/lib/libale${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\ale.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\ale.lib exit 1  # [win]

about:
  home: https://github.com/USGS-Astrogeology/ale
  license: Unlicense
  license_file: LICENSE
  summary: Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data.

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
