{% set name = "ale" %}
{% set version = "0.8.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0466d779f6d2d5221043b02252cc1a4ab6026eec6665b9216b276a5767aecdae
  patches:
    - patches/python_36.patch  # [py==36]

build:
  number: 1
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - eigen
  host:
    - python
    - nlohmann_json
    - pip
  run:
    - networkx
    - nlohmann_json
    - numpy
    - pvl
    - python
    - python-dateutil
    - scipy >=1.2.0
    - spiceypy >=2.3.0
    - pyyaml

test:
  imports:
    - ale
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - test -e $PREFIX/lib/libale${SHLIB_EXT}
    - test -e $PREFIX/include/ale/Load.h

about:
  home: https://github.com/USGS-Astrogeology/ale
  license: The Unlicense
  license_file: LICENSE
  summary: Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data.

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
